server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: S@lut3m!!142536
    driverClassName: org.postgresql.Driver
    tomcat:
      max-active: 1000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false

  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB